name: mobile_computing_smart_home
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  fluentui_icons: ^1.0.0
  fluentui_system_icons: ^1.1.189
  api_cache_manager: ^1.0.2
  snippet_coder_utils: ^1.0.12
  sms_autofill: ^2.2.0
  path_provider: ^2.0.11
  http: ^0.13.5
  cupertino_icons: ^1.0.2
  hexcolor: ^3.0.1
  firebase_core: ^2.5.0
  firebase_auth: ^4.2.6
  firebase_database: ^10.0.11
  cloud_firestore: ^4.4.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  hive_generator: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - images/

  fonts:
    - family: Oxanium
      fonts:
        - asset: fonts/Oxanium-VariableFont_wght.ttf
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-VariableFont_wght.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
